export const Users = [
    {
      id:1,
      profilePicture: "assets/person/4.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "/assets/person/8.jpeg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "assets/person/7.jpeg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "/assets/person/8.jpeg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "assets/person/7.jpeg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "assets/person/4.jpeg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "/assets/person/8.jpeg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "assets/person/7.jpeg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Enjoying some groovy tunes",
      photo: "assets/person/post/in case cd.gif",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/person/post/rainbow pixel gif.gif",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc: "just wokup",
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "...",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc: "working hard, or hardly working...",
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/person/post/glowing moon.png",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      desc: "What should i eat todayyy",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "first post",
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];